---
title: "Flexibility"
author: "Bill Xu"
date: "2022-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=F}
library(haven)
library(tidyr)
library(dplyr)
library(lme4)
library(lmerTest)
library(emmeans)
library(psych)
library(MuMIn)
```

```{r load_data, include=F}
data_plan <- read_csv("data_plan.csv")
data_participant <- read_csv("data_participant.csv")
```

# Weights

```{r weights, include=T}
describeBy(data_participant[-1:-2], group=data_participant$Prof, fast=T)
```

# Importance of Predictors

```{r regression, include=F}
model_all <- lmer(Total ~ Factor_1 + Factor_2 + Factor_3 + Factor_4 + Factor_5 + Factor_6 + Factor_7 + Factor_8 + Factor_9 + Factor_10 + Factor_11 + (1|ID), data = data_plan)

data_plan_exp <- data_plan %>% filter(Prof=="Very Experienced: architecture professional")

model_exp <- lmer(Total ~ Factor_1 + Factor_2 + Factor_3 + Factor_4 + Factor_5 + Factor_6 + Factor_7 + Factor_8 + Factor_9 + Factor_10 + Factor_11 + (1|ID), data = data_plan_exp)

#Burnham, K. P. and Anderson, D. R (2002) Model selection and multimodel inference: a practical information-theoretic approach. 2nd ed. New York, Springer-Verlag.

data_plan_exp_noNA <- data_plan_exp %>% drop_na()

model_exp_noNA <- lmer(Total ~ Factor_1 + Factor_2 + Factor_3 + Factor_4 + Factor_5 + Factor_6 + Factor_7 + Factor_8 + Factor_9 + Factor_10 + Factor_11 + (1|ID), data = data_plan_exp_noNA, na.action = "na.fail", REML = F)

ms <- dredge(model_exp_noNA)

sw(ms)
```